# Databricks notebook source
# MAGIC %md # Visualize the AWS graph generated by Altimeter

# COMMAND ----------

# MAGIC %pip install kglab rdflib pyvis

# COMMAND ----------

# MAGIC %sh ls -R /dbfs/tmp/altimeter_single_account

# COMMAND ----------

from rdflib import Graph
import kglab

# COMMAND ----------

g = Graph()
base_path = "/dbfs/tmp/altimeter_single_account/20221028/1666966271/cae383f3-dc96-40f4-8b63-99164fc2eae3/"
g.parse(F"{base_path}/master.rdf")
len(g)

# COMMAND ----------

kg = kglab.KnowledgeGraph(import_graph=g)

# COMMAND ----------

import pandas as pd
pd.options.display.max_colwidth = 200
pd.options.display.max_rows = 200

# COMMAND ----------

sparql = """
SELECT  ?s ?pp ?x
WHERE {
    ?s ?p <arn:aws::::account/997819012307> .
    ?x ?pp ?s
}
LIMIT 1000
"""
display(kg.query_as_df(sparql=sparql))

# COMMAND ----------

sparql = """
SELECT  (count(distinct ?s) as ?count)
WHERE {
    ?s <alti:account> <arn:aws::::account/997819012307>
}
"""
display(kg.query_as_df(sparql=sparql))

# COMMAND ----------

displayHTML(kglab.SubgraphTensor(kg).build_pyvis_graph().generate_html())
